Add covid and surgery forms
openmrs/openmrs-distro-referenceapplication pull request #626
Opened 2022-06-27 19:42 UTC by reagan-meant

2022-06-28 05:41 UTC, ZacButko approved these changes
Thanks @reagan-meant

2022-06-28 05:41 UTC, ZacButko commented on package/config/configuration/ampathforms/poc_covid19.json
> +    "version" : "1",
Seems there's some weird spacing going on. Is it possible to run this through a code formatter like Prettier?

2022-06-28 05:47 UTC, reagan-meant commented on package/config/configuration/ampathforms/poc_covid19.json
> +    "version" : "1",
Done

2022-06-28 11:18 UTC, rbuisson requested changes

2022-09-01 09:23 UTC, rbuisson commented
@reagan-meant  could we get this one done? There is only little changes to be made it seems.

2022-09-09 12:39 UTC, rbuisson approved these changes
Just pasted properly formated JSONs.
Tried locally and this works fine.
Thanks @reagan-meant .

2022-09-09 12:40 UTC, merged