(feat) Group Session Meta
openmrs/openmrs-distro-referenceapplication pull request #632
Opened 2022-09-09 14:39 UTC by ZacButko

This adds concepts needed by the group session feature.

2022-09-09 14:41 UTC, reagan-meant requested changes

2022-09-09 14:41 UTC, reagan-meant commented on distro/configuration/concepts/group_session_meta.csv
> +e2559620-900b-4f66-ae41-0b9c4adfb654,,,Session Name,Nombre de sesi�n,Name,Nombre,Session Name,Misc,N/A,,,,,,,,,,,
Change the date type to Text

2022-09-09 14:41 UTC, reagan-meant commented on distro/configuration/concepts/group_session_meta.csv
> +f1a2d58c-1a0e-4148-931a-aac224649fdc,,,Practitioner,Facultativo,Practitioner,Facultativo,Practitioner,Misc,N/A,,,,,,,,,,,
Change the date type to Text

2022-09-09 14:41 UTC, reagan-meant commented on distro/configuration/concepts/group_session_meta.csv
> +fa8fedc0-c066-4da3-8dc1-2ad8621fc480,,,Session Notes,Notas de la sesi�n,Notes,Notas,Session Notes,Misc,N/A,,,,,,,,,,,
Change the date type to Text

2022-09-09 14:46 UTC, ZacButko commented on distro/configuration/concepts/group_session_meta.csv
> +fa8fedc0-c066-4da3-8dc1-2ad8621fc480,,,Session Notes,Notas de la sesi�n,Notes,Notas,Session Notes,Misc,N/A,,,,,,,,,,,
Ok changes pushed. Is this correct now?

2022-09-09 14:51 UTC, ZacButko commented
@reagan-meant did I make the changes correctly?

2022-09-12 14:58 UTC, reagan-meant approved these changes

2022-09-13 04:13 UTC, merged