O3-1557: run e2e tests on the 3.x branch at openmrs-distro-reference application
openmrs/openmrs-distro-referenceapplication pull request #644
Opened 2022-10-07 09:23 UTC by jnsereko

I strongly stand by us running all tests rather than smoke tests.  I have honestly failed to sieve out what test is more worth than the other.  

I will also create another workflow to run smoke tests so devs can optionally skip (ignore) the all e2e tests workflow in case they are overwhelmed by the reds while merging. 

cc @dkayiwa @gracepotma @ibacher

2022-10-07 17:32 UTC, ibacher requested changes
I think this PR is mis-targetted. In particular, this should run as part of the Bamboo job rather than GitHub Actions here. Triggering this as part of GitHub Actions means it will only run on PRs and merges _to this repo_. Most such merges are adding metadata to the RefApp and these tests add very little value there. However, the Bamboo job is currently triggered on every commit to the RefApp frontend repo, so it will be able to catch breaking changes after they are committed.

PS Thanks @jnsereko for all your work on this. It's really just a matter of making sure we run these tests at the right point.

2022-10-07 17:32 UTC, ibacher commented on .github/workflows/refapp-3x-vitals-and-biometrics.yml
> +        run: cd openmrs-test-3refapp && yarn install
```suggestion
        run: cd openmrs-test-3refapp && yarn install --immutable
```

2022-10-07 17:32 UTC, ibacher commented on .github/workflows/refapp-3x-vitals-and-biometrics.yml
> +          path: packages/cypress/cypress/videos
```suggestion
          path: openmrs-test-3refapp/packages/cypress/cypress/videos
```

2022-10-10 14:55 UTC, jnsereko commented
thank you so much for the response @ibacher 
I kindly request you and @dkayiwa to help me an we follow up on this at https://openmrs.slack.com/archives/CP343JH1R/p1665404314967979

2023-10-20 23:39 UTC, jayasanka-sack commented
Closing this PR as it has already been addressed in https://issues.openmrs.org/browse/O3-2493

2023-10-20 23:39 UTC, closed without merging