KH-53:  Improve error dialog messages when entering incorrectly formatted IDPoor
openmrs/openmrs-distro-referenceapplication pull request #682
Opened 2023-01-25 15:58 UTC by kazlaw

https://issues.openmrs.org/browse/KH-53

2023-02-01 11:03 UTC, rbuisson requested changes

2023-02-01 11:03 UTC, rbuisson commented on distro/configuration/patientidentifiertypes/cambodia-identifiers.csv
> +177c01be-789a-4c47-9515-3e6b092d4322,,IDPoor,IDPoor,លេខសម្គាល់ប័ណ្ណក្រីក្រ (ប័ណ្ឌមូលនិធិសមធម៌),IDPoor (Equity Card number),FALSE,[0-9]{8}-[0-9]{4}|[0-9]{8}-5[0-9]{3}|[0-9]{8}-9[0-9]{3}|[0-9]{3}-[0-9]
Why 3x the double quotes?

2023-02-02 06:30 UTC, kazlaw commented on distro/configuration/patientidentifiertypes/cambodia-identifiers.csv
> +177c01be-789a-4c47-9515-3e6b092d4322,,IDPoor,IDPoor,លេខសម្គាល់ប័ណ្ណក្រីក្រ (ប័ណ្ឌមូលនិធិសមធម៌),IDPoor (Equity Card number),FALSE,[0-9]{8}-[0-9]{4}|[0-9]{8}-5[0-9]{3}|[0-9]{8}-9[0-9]{3}|[0-9]{3}-[0-9]
Let me have this rectified,

2024-02-21 18:24 UTC, samuelmale commented
Closing this because it's not refApp specific

2024-02-21 18:24 UTC, closed without merging